name: CI

on:
  pull_request:
    branches: [ "master", "main" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "master", "main" ]
    paths-ignore: [ "docs/**" ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    services:
      db_service:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: stats_collector
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
          #----------------------------------------------
          #       check-out repo and set-up python
          #----------------------------------------------
          - name: Check out repository
            uses: actions/checkout@v3
          - name: Set up python
            id: setup-python
            uses: actions/setup-python@v4
            with:
              python-version: 3.10.5
          #----------------------------------------------
          #  -----  install & configure pipenv  -----
          #----------------------------------------------
          - name: Install dependencies with pipenv
            run: |
              pip install pipenv
              pipenv install --deploy --dev
              pipenv run mypy --install-types --non-interactive
          - name: Run lint
            run: make lint
          - name: Run tests
            run: make test